# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('happiness', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
