# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='cum_vol',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='data',
            name='las_vol',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='data',
            name='new_vol',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='data',
            name='raw_vol',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
