# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='las_vol',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='new_vol',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
