# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20170224_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
