# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20170224_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='cum_vol',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='raw_vol',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
